### PR TITLE
bitmap fonts 

### PR DESCRIPTION
**Pull request by catfact**
ok, i decided i wanted a monospace font, and fell in a rabbit hole

- theres a lot of great monospace pixel fonts suitable for small blocky screens
- many/most are in bitmap formats, don't translate well to truetype
- cairo happily reads `.bdf` and `.pcf`, but they look crummy when rescaled
- that's fine but means you kinda want `font-6.bdf`, `font-8.bdf`, `font-10.bdf`, &c
- it gets silly with the current system of magic numbers for selecting fonts

so:

- i added a large number of .bdf files to `resources/bmp`. but i don't know how useful this really is; it's really painful to select one that looks good with the current system. most of them look best at 12px or so. 

- 'tom-thumb' i think is worth keeping regardless; it's the old palmpilot font and looks nice at 6px.

--------

- added bitstream-vera TTF fonts while i was at it.

-------

meanwhile, a separate question/issue rolled in here:

- noticed that antialiasing for fonts wasn't changed with `screen_aa`; so, added that, but not sure it's desired.
- there was also an inconsequential leak of a `cairo_font_options_t` pointer.

### CODE REVIEW

**Comment by catfact** [comment]
full list at the moment: 
```
  0: 04B_03__.TTF
  1: liquid.ttf
  2: Roboto-Thin.ttf
  3: Roboto-Light.ttf
  4: Roboto-Regular.ttf
  5: Roboto-Medium.ttf
  6: Roboto-Bold.ttf
  7: Roboto-Black.ttf
  8: Roboto-ThinItalic.ttf
  9: Roboto-LightItalic.ttf
  10: Roboto-Italic.ttf
  11: Roboto-MediumItalic.ttf
  12: Roboto-BoldItalic.ttf
  13: Roboto-BlackItalic.ttf
  14: VeraBd.ttf
  15: VeraBI.ttf
  16: VeraIt.ttf
  17: VeraMoBd.ttf
  18: VeraMoBI.ttf
  19: VeraMoIt.ttf
  20: VeraMono.ttf
  21: VeraSeBd.ttf
  22: VeraSe.ttf
  23: Vera.ttf
  24: bmp/tom-thumb.bdf
  25: bmp/creep.bdf
  26: bmp/ctrld-fixed-10b.bdf
  27: bmp/ctrld-fixed-10r.bdf
  28: bmp/ctrld-fixed-13b.bdf
  29: bmp/ctrld-fixed-13b-i.bdf
  30: bmp/ctrld-fixed-13r.bdf
  31: bmp/ctrld-fixed-13r-i.bdf
  32: bmp/ctrld-fixed-16b.bdf
  33: bmp/ctrld-fixed-16b-i.bdf
  34: bmp/ctrld-fixed-16r.bdf
  35: bmp/ctrld-fixed-16r-i.bdf
  36: bmp/ProggyCleanSZ.pcf
  37: bmp/ProggySquareSZ.pcf
  38: bmp/ProggyTinySZ.pcf
  39: bmp/scientifica-11.bdf
  40: bmp/scientificaBold-11.bdf
  41: bmp/scientificaItalic-11.bdf
  42: bmp/ter-u12b.bdf
  43: bmp/ter-u12n.bdf
  44: bmp/ter-u14b.bdf
  45: bmp/ter-u14n.bdf
  46: bmp/ter-u14v.bdf
  47: bmp/ter-u16b.bdf
  48: bmp/ter-u16n.bdf
  49: bmp/ter-u16v.bdf
  50: bmp/ter-u18b.bdf
  51: bmp/ter-u18n.bdf
  52: bmp/ter-u20b.bdf
  53: bmp/ter-u20n.bdf
  54: bmp/ter-u22b.bdf
  55: bmp/ter-u22n.bdf
  56: bmp/ter-u24b.bdf
  57: bmp/ter-u24n.bdf
  58: bmp/ter-u28b.bdf
  59: bmp/ter-u28n.bdf
  60: bmp/ter-u32b.bdf
  61: bmp/ter-u32n.bdf
  62: bmp/unscii-16-full.pcf
  63: bmp/unscii-16.pcf
  64: bmp/unscii-8-alt.pcf
  65: bmp/unscii-8-fantasy.pcf
  66: bmp/unscii-8-mcr.pcf
  67: bmp/unscii-8.pcf
  68: bmp/unscii-8-tall.pcf
  69: bmp/unscii-8-thin.pcf
```

**Comment by catfact** [comment]
(hrm, some of the pcfs are broken btw)

**Comment by tehn** [comment]
i suspect that additional font anti-aliasing is not generally desired. aren't they anti-aliased by default on rendering (ie roboto?) the standard menu font (#1) certainly would suffer. but i haven't tested this PR yet so perhaps i'm not getting it

**Comment by catfact** [comment]
Sub pixel anti aliasing was always on for fonts. I made it toggle with other AA setting. Menu font unaffected

**Comment by tehn** [comment]
ok rad. thank you for adding more fonts!

re: magic numbers, i could add a reverse lookup table in lua if we want to reference fonts by name

**Comment by catfact** [comment]
pushed small change removing a few fonts that just didn't work.

also: here's a test script that just lets you scrub all faces, all sizes, and toggles AA:
https://github.com/catfact/zebra/blob/master/fonts.lua

things i noticed:

- OK, i take it back; AA does affect the appearance of the menu font (*04B_03*), but only when it's scaled to a non-multiple of 8, only subtly, and it looks bad either way in that scenario.

- other `.ttf` (vector) fonts are affected by AA (similarly); `.bdf` (bitmap) fonts are not affected by it (at least for the two settings that are toggled - "sub-pixel" and "none.")

- there are a few fonts where i can't see the difference between variants (e.g. 40/41, 42/44, 54/56); should strip these out.

- only font face no. 25 (**tom-thumb**) looks decent at 6pt.

- most of the `bdf`s are scaled for 16pt, which doesn't always mean that the characters are 16px high (varies a lot.) dunno how many large monospace  fonts this system really needs.

anyway feel free to remove whatever. 

i do think a reverse lookup table would help, so scripts are less likely to break if this table changes. (i'd just generate it from the c code here: https://github.com/monome/norns/pull/795/commits/7fd164dbe5928b6556de89600985b2cfe6ebb777#diff-0dd29230b8cae8890be478550d97b144L248)

---------

oh, re: licensing,

most of these and many others are collected here:
https://github.com/Tecate/bitmap-fonts
many of the fonts in that repo have licenses (e.g. GPL2), but none of these do.
i guess it would be nice to credit the authors where possible.

exception is **tom-thumb**, which comes from here:
https://robey.lag.net/2010/01/23/tiny-monospace-font.html

that page implies that they'd like it to be CC0 or CC-BY 3.0, but also includes this MIT license
http://vt100.tarunz.org/LICENSE

so, i should add that... which i guess means separate subdir. blerg...

**Comment by tehn** [comment]
that sounds good then (that aa doesn't affect main font at normal sizes)

so stoked about tom-thumb. there are some rad screen shots in the comments on that page, ie google running on lynx with a 128x64 pixel screen

**Comment by tehn** [comment]
tested this out just now with your script. it's fantastic! i think the aa behavior is perfectly normal and good/predictable.

freakin love font#25

**Comment by tehn** [comment]
i'm going to merge this and then i'll update the LICENSE with some specifics per font group

**Comment by itsyourbedtime** [comment]
I'd suggest adding Berkelium font, which looks quite cool
http://www.kreativekorp.com/software/fonts/c64.shtml#berk

**Comment by artfwo** [comment]
Its license restricts modifications and selling copies though, could be GPL-incompatible.

**Pull request merged**
