### PR TITLE
update softcut

### PR DESCRIPTION
**Pull request by catfact**
update softcut submodule

### CODE REVIEW

**Review by tehn — APPROVED** [review]

**Comment by tehn** [comment]
augh was overenthusiastic, something is not right. will create a proper test scenario.

**Comment by catfact** [comment]
alright I will look more closely

**Comment by catfact** [comment]
i am not seeing any unexpected behavior....

**Comment by catfact** [comment]
pushed another change to reset fade time as well. 

if you had long fade time, it might be confusing in something like the `recdub` study. because changing the rate alone would do this:
- you hear a sweep in buffer playback pitch over the duration of the xfade
- on repeated passes, the playback pitch sounds normal because write- and read-rates are identical (and pre==0)

so it sounds almost like the rate rises, and then decays back to unity.

**Comment by tehn** [comment]
this makes sense, and sounds like what i was witnessing

**Pull request merged**
