### PR TITLE
Vu decay

### PR DESCRIPTION
**Pull request by catfact**
fix the dumb typo that made vu levels non-monotonic.

along the way, some refactors and changes to how meter levels are windowed and accessed

now it uses a leaky integrator with separate rise/fall times, which are hardcoded in `PeakMeter.h` and which are currently set to a nonstandard [0, 300ms] - so we emphasize peak level.

### CODE REVIEW

**Comment by catfact** [comment]
believe it or not i am actually going 'hardware first' now unless the changes are complex enough to benefit from static anlaysis and whatnot. 

so i have actually looked at this and it looks fine - messy git history notwithstanding

**Comment by tehn** [comment]
yikes. running `./waf` on norns:

```
[42/48] Compiling crone/src/Taper.cpp
In file included from ../crone/src/Taper.h:3:0,
                 from ../crone/src/Taper.cpp:1:
../crone/src/Utilities.h: In function ‘float crone::smooth1pole(float, float, float)’:
../crone/src/Utilities.h:37:31: internal compiler error: Illegal instruction
         return x + (x0 - x) * b;
                               ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
```

did a `./waf clean` then `./waf` just in case:

```
[38/48] Compiling crone/src/softcut/TestBuffers.cpp
g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.

Waf: Leaving directory `/home/we/norns/build'
Build failed
 -> task in 'crone' failed with exit status 4 (run with -v to display more information)
```

???

then ran `./waf -v` and it succeeded???

any ideas? never seen `waf` fail. like this.

**Comment by catfact** [comment]
no idea. gcc bug i guess. haven't had any such problems here with multiple compiles on norns.

**Comment by tehn** [comment]
oy. and just did a clean build. no idea, sorry for the noise.


these meters look a million times better!! super legit. thank you!

**Pull request merged**
