### PR TITLE
fix softcut.defaults() (again)

### PR DESCRIPTION
**Pull request by AndrewShike**
sorry for double PR !

should be `state[i] = {}` not `state[i] = 0;`

attempted to clean up `level_input_cut`& `level_cut_cut`. I think this was using multiple assignment [wrong](https://www.lua.org/pil/4.1.html), the value was just `i`. made them arrays of zeros, perhaps more helpful

tested via copy and paste this time

### CODE REVIEW

**Comment by tehn** [comment]
good catch. fix the merge conflict first?

**Comment by AndrewShike** [comment]
I think I did it ... learning !

**Comment by AndrewShike** [comment]
also: I'm showing `level_input_cut` defaulting to 0, but not sure if that's actually the case.

**Comment by catfact** [comment]
this `defaults()` function looks extremely messed up in many additional ways

**Comment by catfact** [comment]
just let me fix it please

**Pull request closed without merging**
