### PR TITLE
grid rotation

### PR DESCRIPTION
**Pull request by okyeron**
Adds function to rotate grid.

```
local g = grid.connect()
g.rotation(1) -- 0,1,2,3 are options for 0,90,180,270
```

Needs menu.lua work to make it a configurable setting in menu.

### CODE REVIEW

**Comment by tehn** [comment]
nice!! have you tested this on hardware?

i can do the menu UI.

**Comment by okyeron** [comment]
I've only got my teensy grid to test on - and it works at 90 degrees for me. 

The 180 and 270 rotations don't work right on my diy grid from the Monome Home Maxpat, so there's some other bug in my grid code so I cant confirm they are working properly.

**Comment by tehn** [comment]
ok i'll test it out on hardware first

**Comment by tehn** [comment]
works great! thank you!

**Pull request merged**
