### PR TITLE
likely fix for SEGV on USB device removal

### PR DESCRIPTION
**Pull request by ngwese**
i spent a bit of time trying to get to the bottom of #920 - in particular looking at the changes which were made to the device management for handle multiple midi endpoints.

i believe the problematic change was the introduction of `dev_remove_node`. the `dev_remove_node` function combined existing deletion event posting, `dev_delete`, and device list node removal _with a call to `dev_lookup_path` starting from the device list node being removed/deleted_. the `dev_lookup_path` function walks the device list looking for the first node which matches the given path. in the case of `dev_remove_node` that lookup was started from the device node which was previously passed to `dev_delete`. the `dev_delete` function does several things but in particular it frees memory allocated for the device "path" string pointed to by the node. the net effect is a use after `free()` for one of the strings being fed to `strcmp(...)` and a potential source of crashing.

this change:
- factors out the call from `dev_lookup_path` from `dev_remove_node`
- renames `dev_remove_node` to `dev_list_remove_node` for clarity
- only performs exhaustive searches for multiple device nodes in the case of midi

open questions
- in the case of *midi* devices the repeated searching for matching devices always starts from the head node in the list which means that removal has O(num_endpoints * total_num_devices) complexity (i.e. exponential). in practice this didn't seem to be noticeable when hot pulling 1x grid, 2x single endpoint midi, and 1x four endpoint midi devices...
- the complexity could be reduced to O(num_endpoints) if `insque` and `remque` guaranteed that nodes wouldn't be moved in memory when the list was being modified. i think this is the case but the man page didn't make any statements regarding pointer stability.

### CODE REVIEW

**Comment by ngwese** [comment]
update: fair amount of interactive hot plug testing with multiple grids and midi devices and usb hubs - no crashing. previously with this same setup i was crashing 80% of the time i removed a usb device.

**Comment by pq** [comment]
💎 💎 💎

**Comment by ryanlaws** [comment]
Excellent!!!

**Comment by ryanlaws** [comment]
Thank you for your testing and for fixing this. This bug made me sad whenever I thought about it and I had a hard time reproducing it. I'm going to sleep a little easier now.

**Comment by okyeron** [comment]
Query - is this related to the `usb 1-1.3: urb status -32` errors I see in `dmesg` when disconnecting USB devices (on Raspi)?

**Comment by ngwese** [comment]
no - this change is specifically focused on preventing `matron` from crashing when USB devices are disconnected.

the significance of the `urb status -32` and the sequence of events which leads to them is a separate line of investigation.

**Comment by okyeron** [comment]
I did not see an issue for the  `urb status -32` thing so please let me know if/where I can help with that - I seem to be able to reproduce that pretty regularly.

**Pull request merged**
