### PR TITLE
crow integration

### PR DESCRIPTION
**Pull request by tehn**
initial crow device integration. (crow is a usb device, eurorack CV interface with onboard lua interpreter). see https://github.com/monome/crow

### status

- crow add/remove works, auto-attached. only one unit is supported at once, though the device lib could do more, it'd require some SYSTEM MENU integration similar to grids/midi/etc with vports.
- command set:

```
-- send arbitrary lua line to be executed by crow
crow.send("print('hello')")
-- set output 1 to 3.0V
crow.output[1].volts = 3.0
-- set input mode to 'none'
crow.input[1].mode("none")
-- query input 1
crow.input[1].query()
-- redefine input event function
crow.input[1].receive = function(n,v) ... end
```

### todo

- [x] `^^` commands are not working ie `^^version` suggesting some some of lower-level comm problem
- [x] crow is having some buffer trouble, ie adjacent characters are sometimes copied over one another
- [x] device detection is _very_ dumb, just claiming `ttyACM?` devices. needs to perform an id handshake before adding them as a device.
- [x] ~~`dev_crow_send` should maybe be threaded as to not block~~ (doesn't seem like a problem)
- [x] incoming data is NOT buffered. if an incoming event is not read before the next comes in, the previous just gets overwritten... see `dev_crow` struct. 
- [x] input/output syntax is different than onboard crow, which uses indexed arrays ie input[1].mode
- [x] output asl not implemented
- [x] sloppy globals. `ret_cv` and `change` should get moved to a table (use a substitution instead of substring when parsing incoming crow messages for ^^ check)
- [x] ansible i2c commands

### CODE REVIEW

**Comment by trentgill** [comment]
Regarding the device detection being dumb, i'm doing the same thing in the Max object for crow support, so if it's a lua solution would be great to get that into the crowmax.lua object in crow too.

**Comment by okyeron** [comment]
Using `.node_pattern = "/dev/ttyACM*"` will cause conflicts with teensy based devices connecting to norns. 

see #525

**Comment by tehn** [comment]
crow will have a serial handshake before using the device, but it will attempt this handshake on any path that matches. failure is expected for non-crow devices, and they will then be released.

**Comment by okyeron** [comment]
OK - but as the code reads to me right now in `device_monitor.c` a teensy device like my grid or arc clone would be identified as `.sub_name = "crow"` instead of `.sub_name = "tty"`

Is there a better way to filter those devices at that stage?

**Comment by tehn** [comment]
yes we'll need to find a solution for that. honestly it's difficult considering you're talking about code that isn't in master right now. can you make a more complete proposal for device interaction in https://github.com/monome/norns/issues/525 ?

**Comment by simonvanderveldt** [comment]
Can't we set `.sub_name = tty` when we reach this point?
> failure is expected for non-crow devices, and they will then be released.

**Comment by okyeron** [comment]
Understood. I was just hoping to get this "on the radar" since I saw the note about device detection being "dumb" and grabbing all ttyACM* devices.

I'll try to look at this further and see if I can propose something, but I don't really know C enough to code a solution. 

Seems like checking node_pattern first and then getting more information to determine if it should be tty, crow, etc. would be good.

**Pull request merged**
