### PR TITLE
conditionally compile link clock bindings

### PR DESCRIPTION
**Pull request by artfwo**

### CODE REVIEW

**Comment by catfact** [comment]
i think there are some other calls too?

```
matron/src/main.c.1.o: In function `main':
/home/we/norns/build/../matron/src/main.c:79: undefined reference to `clock_link_start'
matron/src/weaver.c.1.o: In function `_clock_link_set_quantum':
/home/we/norns/build/../matron/src/weaver.c:1444: undefined reference to `clock_link_set_quantum'
matron/src/weaver.c.1.o: In function `_clock_link_set_tempo':
/home/we/norns/build/../matron/src/weaver.c:1437: undefined reference to `clock_link_set_tempo'
collect2: error: ld returned 1 exit status
```

maybe i'm doing something wrong... i did `waf clean`, `configure`, `build`

**Comment by artfwo** [comment]
strange, in main they're already surrounded by #ifdefs

**Comment by catfact** [comment]
yea sorry must be on my end

**Comment by artfwo** [comment]
just reproduced on my end as well - must be some bad waf scripting from my side, working on it.

**Comment by artfwo** [comment]
sorry, haven't tested the no-link configuration enough. should build fine now both with and without link.

**Pull request merged**
