### PR TITLE
add clock.create, clock.suspend

### PR DESCRIPTION
**Pull request by ngwese**
allows additional control over how and when clock coroutines
execute through explicit use of suspend and resume along side
existing sleep and sync scheduling

- automatically cancels clocks when their coroutine completes
- print warning when a canceled clock is resumed

### CODE REVIEW

**Comment by ngwese** [comment]
marking this as do not merge for now. i'm going to experiment more deeply to validate the idea.

**Comment by artfwo** [comment]
@ngwese but dead coroutines cleanup looks good to go, how about creating a separate PR for it?

**Comment by tehn** [comment]
any movement on this one?

**Comment by ngwese** [comment]
i’m happy with the addition however the code i was working on which used this has been simplified such that it isn’t strictly necessary.

the use cases i was imagining generally involved creating a coroutine in one part of of a script and running/suspending it another  part without the two parts needing to know about each other. suspend is useful in this context because the consumer of the preconstructed clock does have to have the knowledge to recreate it. all of this is doable by wrapping an object around the clock but that seems like more ceremony than might be desirable for small scripts. 

i have been running with these changes for two days now with no ill effects. 

i’d be inclined to merge unless there is strong concerns.

**Comment by tehn** [comment]
i see the value in this, even if it's an more niche use case.

**Comment by ngwese** [comment]
pushing forward with merging this.

`create` has proven useful because it allows one to pass the coroutine/clock id into the clock itself (via `resume`) and the clock can subsequently signal other parts script of changes about itself (like that it is sync'd and entering its loop or suspending itself). being able to just the clock id removes the need to create another associative table of arbitrary id => clock id in order to identity which clock is signaling.

`suspend` is useful when one wants to suspend/resume a coroutine/clock is built around a loop which is stepping via an infinite iterator (treating it like an event queue) until some external variable signals it to stop. if the queue is full of note like values one likely wants the note off to be sent before the coroutine is stopped. keeping this book keeping inside the coroutine and allowing it to suspend itself is easier than doing the coordination outside of the coroutine.

the clock abstraction is very cool and it is fun to treat clocks less as clocks and more as little actors which are sources of timed events.

**Pull request merged**
