### PR TITLE
single threaded coroutine wakeup scheduler

### LINKED ISSUE #1273: clock: crow + MIDI external clock sources double-trigger clock.sync(1)
[test script](https://llllllll.co/uploads/short-url/fphQ0hdySEN6OkhK6H2yhTmPGUU.lua)

*setup:*

- connect to maiden
- attach a MIDI or crow clock source to norns
- nav to EDIT > CLOCK and choose midi or crow
  - MIDI tests: OP-Z, UM-ONE, MOTU UltraLite mk4
  - crow tests: Teletype with steady 500ms pulse + crow in div set to 1
- ensure the tempo displayed matches the expected tempo
- run the script

*script details:*

- script starts by truncating the current clock beat number and assigning it to a variable count
- a coroutine is established
- the coroutine uses `clock.sync(1)` to sync to each beat
- each beat increments the count variable by 1
- each beat prints the current beat number
- in theory, these two values should remain the same (understanding that the printed clock beat might be +0.00x ahead)

*expected results:* in the repl, the integer of the left value (clock beat) matches the right value (count)

*control:* running script with internal clock or Link clock provides expected results (for at least 500 beats)

*actual results*: clock steps are somehow double-tapping, which double-increments the count value

```lua
1181.0002472464	1181
1182.000157767	1182
1183.0018666615	1183
1183.9966417216	1184
1184.0018485279	1185
1185.0002404991	1186
1186.0002296293	1187
1187.0005070127	1188
1188.0003569899	1189
1189.000229808	1190
1190.0024096313	1191
1190.9967660519	1192
1191.0018336364	1193
1192.0001773595	1194
1193.0008779371	1195
1194.0000049084	1196
1195.0005623592	1197
1196.0002397995	1198
```

*impact:*

- if a script uses a coroutine to advance a counter to determine a 16-beat bar, then the counter would hit 16 beats at the 14th beat
- if a script is just simply re-triggering a synth voice on a steady pulse, the voice is re-triggered and sounds accented

### PR DESCRIPTION
**Pull request by artfwo**
this PR replaces the multi-threaded coroutine resume event scheduler with a single-threaded implementation, where a single scheduler thread is constantly tracking scheduled sync and sleep wakeups with ~1 millisecond resolution and sending clock resume events when necessary.

effectively, this enables smooth(er) midi and crow beat tracking and smooth switching between clock sources when using the clock lib and fixes #1273.

i haven't done any proper benchmarking, but matron CPU usage seems to be roughly the same with this PR (with a few coroutines running concurrently), occasionally there's an increase from 4% to 5%, but it doesn't seem like a huge issue.

### CODE REVIEW

**Comment by tehn** [comment]
this is looking great, thank you for concerted effort!

**Comment by artfwo** [comment]
@tehn this is currently ready for review, as feature-wise this is complete and is a huge improvement over the previous scheduler. i'm going to do a few cosmetic changes in this or a follow-up PR and implement better handling of transport restarts next.

**Comment by tehn** [comment]
@artfwo fantastic! i'll run through a bunch of tests. @dndrks could you also give this a final run?

if we decide so, we could actually do a `beta` build (now that norns update allows for switching between installs) if we'd like a broader test pool

**Comment by ngwese** [comment]
i can give `tambla` a try as well since it is heavily coroutine based. @artfwo - are there areas in particular you'd like people to focus?  syncing to incoming midi clock?

**Comment by artfwo** [comment]
well, this should definitely fix issues with midi and crow, so focusing on them is a good idea, but in general this change affects the whole clock lib, so a test of your scripts' entire functionality with different clock sources might not hurt as well.

**Comment by tehn** [comment]
wonderful that you didn't have to touch the lua API. just reviewed the code, looks great. will get to testing

**Comment by tehn** [comment]
initial midi sync testing looks good!

for internal sync, on tempo change is a reset issued? i can permanently stall the clock by rapidly switching between internal tempos (ie in `awake`, using params menu > clock > tempo and twiddling the knob). this is in the params menu, so it's not specific to `awake`.) the param code is just issuing `clock.internal.set_tempo()` alone

**Comment by artfwo** [comment]
when internal clock tempo changes the internal thread is restarted from the last whole beat, there's no other resets. i might need help with reproducing the issue you found though, as i can't reproduce it (desktop or device) locally. what's the commit you're testing against?

**Comment by tehn** [comment]
checking out via `git fetch origin pull/1338/head:1338`

```
commit 1ba94a21ca23637e28de22186a9db1b6d7cd891f
Author: Artem Popov <artfwo@gmail.com>
Date:   Sun Apr 11 13:18:36 2021 +0200
    rename clock_start_from -> clock_start_from_source
```

repo:

- `./waf configure; ./waf` (to ensure it built clean)
- `systemctl restart norns-*`
- load `awake`
- navigate to PARAMS
- CLOCK / TEMPO, then twiddle with E3 quickly back and forth, hovering around a value. this causes notes to fully drop out until twiddling stops

making a bare-bones repo script now

**Comment by artfwo** [comment]
ok, so this behavior is how internal clock was originally implemented and is a bit out of scope of this PR, so i've opened another one for this and other planned improvements here: #1341

**Review by tehn — APPROVED** [review]

**Pull request merged**
