### PR TITLE
reflection: add pattern save + load

### PR DESCRIPTION
**Pull request by dndrks**
omg, i know, so much `reflection` traffic lately!! but the library is _so_ rad and i thought it'd be nice to include a helper for saving/loading pattern data.

usage:
- save: `my_pattern:save(norns.state.data.."pattern.txt")`
- load: `my_pattern:load(norns.state.data.."pattern.txt")`

@ryleelyman + @sonocircuit : please lemme know if there are any q's or blindspots!

### CODE REVIEW

**Comment by dndrks** [comment]
wait, sorry, cleaning up

**Comment by dndrks** [comment]
ok, cleaned up + ready to go, sorry about that!

**Comment by dndrks** [comment]
ok, good to go, sorry for all the noise, long brain day.

**Review by ryleelyman — APPROVED** [review]
looks great!! love the idea of saving + loading!

**Review by tehn — APPROVED** [review]

**Pull request merged**
