### PR TITLE
[WIP] Softcut output filters

### PR DESCRIPTION
**Pull request by catfact**
added output filter to each softcut voice. the DSP is basically a one-line change, adding commands, OSC and lua is a lot more. 

note that this is a breaking change to OSC command list and lua API! the input and output filters need to be differentiated; i replaced `filter_` with `pre_filter` and `post_filter`

this is completely untested! have not even cleaned up formatting! putting it up just in case anyone has time to get to it before i do (which will be soon but probably not today)

### CODE REVIEW

**Comment by tehn** [comment]
i can help on the c/lua glue!

**Comment by catfact** [comment]
the new parameters use `_norns.cut_param()`, so i don't think new c/lua glue is required, and i updated `softcut.lua` 

the main other thing that needs updating is scripts / libraries that call `softcut.filter_xyz`

**Comment by tehn** [comment]
aha, i see what you mean. this seems done then? just needs doc updates?

breaking change is the addition of `pre_` to the existing filters, correct? pretty sure hardly any scripts use them currently, but good to know.

will test. excited to hear this.

side note: i should implement a `softcut_defaults` OSC message that resets crone instead of sending 400 individual OSC messages...

**Comment by catfact** [comment]
>  this seems done then? just needs doc updates?

it needs _testing_

**Pull request closed without merging**
