### PR TITLE
grid-st

### PR DESCRIPTION
**Pull request by catfact**
support for new grids based on stm32.

-----

this requires that `matron` be linked against `libmonome` built from the `grid-st` branch.

steps i had to take:

- clone `libmonome` and build the testing branch
```
git clone https://github.com/monome/libmonome
cd libmonome
git checkout grid-st
./waf configure && ./waf && sudo ./waf install
```

this will result in `libmonome` being installed at `usr/local/include`, `/usr/local/lib`.

however the norns image also has libmonome installed directly under `/usr`. (i'm not sure how.)

- so i had to change the runtime link behavior:

```
echo '/usr/local/lib' | sudo tee /etc/ld.so.conf.d/libmonome.conf
sudo ldconfig
```

(i also nuked the installation under `/usr` but probably not necessary.)

### CODE REVIEW

**Comment by catfact** [comment]
as of hash `ff77fdb8af4eb7ff5f92f91cf197abf146adb1ec`, seems to be working. 
(was having PEBCAK trouble due to once again forgetting how vports work.)

**Comment by tehn** [comment]
code looks great. will test on hardware when i return!

**Comment by ngwese** [comment]
will give this a test tonight

**Comment by ngwese** [comment]
confirmed working on norns, multiple generations of grids, switching back and forth, hot plug.

dmesg output:

**Review by ngwese — APPROVED** [review]
fwiw i couldn't find a `grid-st` branch in `monome/libmonome`  or a related pull request so i built `grid-st` from `catfact/libmonome`.

otherwise lgtm.

**Comment by tehn** [comment]
merging this. works without updating libmonome.

**Pull request merged**
