### PR TITLE
Fix clip before tape write

### PR DESCRIPTION
**Pull request by catfact**
added hardclipper in tape writer class. 

out-of-range values were wrapping when encoded to fixed point. (seems like pretty bad behavior from libsndfile, but w/e.)

could probably implement the hardclipper more efficiently, without conditionals, but this will get it done.

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
@catfact https://github.com/erikd/libsndfile/issues/294#issuecomment-308981161

**Comment by catfact** [comment]
@simonvanderveldt thanks! cutting through the snark i see the useful hint to try `SFC_SET_CLIPPING`. so, will do that and report back.

**Comment by catfact** [comment]
thanks using `SF_SET_CLIPPING` instead, which is surely more efficient and definitely happens on the right thread. 

NB: have only tested on x64 so far

**Comment by tehn** [comment]
fixes #888 

(will test on hardware today)

**Pull request merged**
