### PR TITLE
[WIP] add worker threads for softcut buffer read/write/clear

### PR DESCRIPTION
**Pull request by catfact**
looking at issue #805

added worker threads from OSC handler functions for buffer read/write/clear.

this is untested. opening PR in case anyone wants to leave feedback before i can get around to it.

### CODE REVIEW

**Comment by catfact** [comment]
hey, we should merge this. any softcut script authors want to verify that it doesn't break stuff? 

seemed ok to me but i haven't tested extensively and don't typically use these functions in my scripts.

basically, you should be able to load / save buffer regions without holding up processing other crone OSC commands.

**Comment by tehn** [comment]
crud, sorry! will test this tonight.

**Comment by tehn** [comment]
ok unfortunately having a hard time getting this to run properly.

- branch is 64 commits behind master, so i merge master first (otherwise all sorts of other things are busted with phase polls)
- crone is quitting at some point after startup. if i run it via `start.sh` i see

```
terminate called without an active exception
```

once the menu shows up.

launching `build/crone/crone` and then `build/matron/matron` (in another window) once the SC handshake times out, i see:

```
entering main loop...
softcut: setting enabled: voice 0: 0
softcut: setting voice output level 0: 0
softcut: setting voice input level 0: 0: 0
softcut: setting voice input level 1: 0: 0
softcut: setting enabled: voice 1: 0
softcut: setting voice output level 1: 0
softcut: setting voice input level 0: 1: 0
softcut: setting voice input level 1: 1: 0
softcut: setting enabled: voice 2: 0
softcut: setting voice output level 2: 0
softcut: setting voice input level 0: 2: 0
softcut: setting voice input level 1: 2: 0
softcut: setting enabled: voice 3: 0
softcut: setting voice output level 3: 0
terminate called without an active exception
softcut: setting voice input level 0: 3: 0
softcut: setting voice input level 1: 3: 0
softcut: setting voice input level 1: 3: 0
softcut: setting enabled: voice 4: 0
softcut: setting voice output level 4: 0
softcut: setting voice input level 0: 4: 0
softcut: setting voice input level 1: 4: 0
Aborted
```

and crone quits. will keep looking.

**Comment by catfact** [comment]
hrm... alright thanks for trying. i will attempt to make some time to revisit...

**Pull request closed without merging**
