### PR TITLE
weaver cleanup

### PR DESCRIPTION
**Pull request by tehn**
made a macro to clean it up

### CODE REVIEW

**Comment by catfact** [comment]
arg, i have several issues with this merge.

**Comment by catfact** [comment]
starting with the fact that it pulls in several unrelated changes from other open PRs that are still in review!

**Comment by tehn** [comment]
i rolled back the open PR changes (accidentally did this work on top of the other branch)

this merge only added the macro cleanup. (i think, unless you see something?)

were there other issues?

**Comment by catfact** [comment]
oh, you're right, sorry.

my only specific issue with the `weaver.c` changes is the macro. there is no reason this shouldn't be a static function that takes the LVM state. the macro assumes the existence of a specific named variable at local scope, which is very brittle.

**Comment by catfact** [comment]
there are a number of other ways we can add helpers to make weaver.c more concise if that is the goal. 

i'll just do another round of changes...

**Comment by tehn** [comment]
ok i see what you're saying. sorry for the trouble.

indeed, i was about to get around to cleaning up globals/etc and scrolling through boilerplate code sidetracked me into this thing

**Comment by tehn** [comment]
untested fix: https://github.com/monome/norns/compare/weaver-macro-fix?expand=1

will be near hardware tomorrow

**Pull request merged**
