### PR TITLE
multiple screen backends with runtime lua configuration

### PR DESCRIPTION
**Pull request by csboling**
This implements #1187 and the approach taken is relevant to #1218.

- Restructure the `screen` code to allow drawing to an SDL window (for instance) instead of a framebuffer device.
- Restructure the input polling code (keys and encoders) for similar configurability. This polling code was moved to `matron/src/hardware/input/gpio.c` since it is only one type of input source that might be used (versus e.g. SDL input). 
- At startup, use a Lua configuration file to determine which hardware devices should be used. This is `~/matronrc.lua` if found, otherwise `~/norns/matronrc.lua` loads the default norns hardware configuration.
- Remove the `-f` framebuffer selection arg to matron as it is no longer used.
- To include SDL in the build, `waf` must be run with `--desktop` to avoid adding a library requirement to norns.
- Note that SDL input does not currently cooperate well with the norns main event loop, further work required to get a fully functional matron-on-desktop-linux working.

### CODE REVIEW

**Comment by ngwese** [comment]
cool, will take a look as i'd like to extend the current screen backend to support off screen rendering and i suspect this might make that simpler.

**Comment by tehn** [comment]
wow, sam, this looks great.

i read through everything, and while i should sit with it longer, my immediate confusion is the code duplication in `fd.c` and `gpio.c` (ie `enc_gpio_poll`)

this also reminds me that i could use further guidance in completing https://github.com/monome/norns/pull/1052 as it's a real drag that screen operations currently are in the same thread as lua, which creates timing lags with heavy-animated scripts

**Comment by csboling** [comment]
>  code duplication in fd.c and gpio.c

Oops, this was just a botched rename at some point -- `fd.c` was not actually included in the `wscript` and was not being compiled. Removed in `49da71c` and merged in the latest changes from `main`.

**Comment by ngwese** [comment]
@tehn - i agree on the note about #1052. it would be good to think about how these changes might affect future on device improvements (if at all)

**Comment by tehn** [comment]
just a heads up @csboling that i haven't forgotten about this, i apologize for the delay

**Comment by ngwese** [comment]
same for me. i started to look through and had some minor suggestions but wanted to give it a proper look before commenting!

**Review by tehn — COMMENTED** [review]
this looks great! (will need a merge `main` first, sorry!)

also a good introduction (for me) to SDL, and the simple lua vm instantiation for the config is very nice. the implementation feels clean, though it does add a level of complexity--- i just learned about `TAILQ` :)

i'll defer to @ngwese and @catfact for further critique

**Comment by tehn** [comment]
resolved and merged #1444

**Pull request closed without merging**
