### PR TITLE
no double free for CLEAR

### LINKED ISSUE #1215: CLEAR script function can freeze sound from SuperCollider
steps to repro:
- load boingg, which uses PolySub
- press K2 to start a bouncing ball
- navigate back to the top-level menu
- while the voice is active (not on its decay), hold K1 and CLEAR the script
- sound will drone until a new script is added

expected: CLEAR silences all output

### PR DESCRIPTION
**Pull request by tehn**
quick fix to make sure the engine is never double-cleared

fixes #1215 better

### CODE REVIEW

**Comment by tehn** [comment]
ps, tested :)

**Comment by catfact** [comment]
give me a moment and i will show what i mean

**Comment by catfact** [comment]
dunno why, but i cannot seem to fetch this branch. will open a new one with my additional fixes to SC side to avoid SC errors from running this with no engine loaded.

**Review by catfact — COMMENTED** [review]
because the SC handler for this command is kinda stale, it will throw errors. some engines may also fail to free resources if they rely on the availability of synchronization functions. (which CroneEngine promises for init / deinit methods.) it can also throw more benign errors when performed repeatedly. 

i'll just open a new PR that buttons up these cases.

**Comment by tehn** [comment]
still wanted to remove this line in script.lua

**Pull request merged**
