### PR TITLE
Bufdiskworker fixes

### PR DESCRIPTION
**Pull request by catfact**
small but potentially important fix for incorrect temp buffer allocation.
i haven't tested this at all yet, but opening for visibility since it's potentially important.

### CODE REVIEW

**Comment by catfact** [comment]
this seems to be working fine. i haven't tested on norns hardware. thing to watch for is memory leaks; i'd use `valgrind --check-leaks` on crone process. but the change is pretty simple so i'm not too worried.

**Comment by tehn** [comment]
will valgrind now

**Comment by catfact** [comment]
no, there's a leak, sorry. (when request duration exceeds source.)
fixing...

**Comment by catfact** [comment]
... better.

**Pull request merged**
