### PR TITLE
audio reset within menu

### PR DESCRIPTION
**Pull request by tehn**
issues systemctl messages for crone.

auto-disables crone when turning on wifi in router mode.

LOG removed from SYSTEM menu.

this is a short-term fix.

### CODE REVIEW

**Comment by tehn** [comment]
while there isn't a proper way to see if NTP caught up, and you have to manually re-enable audio, this is a semi-effective fix for #399

**Comment by tehn** [comment]
pushing this through. comments still welcome.

**Comment by nf** [comment]
👍 

While ideally we'd like to the point where this is unnecessary, having a RESET option in the SYSTEM menu seems like a sound short-term usability improvement.

**Comment by catfact** [comment]
this implementation gives me the creeps - a superuser OS call smack in the middle of the menu spaghetti. we have an `audio` lua module, an `audio.reset` method, it retriggers a matron/crone handshake and makes sure we get engine reports &c! it was a lot of work! can we use that? if it doesn't work correctly can we fix it?

**Comment by tehn** [comment]
sure thing, i'll fix it

**Comment by tehn** [comment]
unfortunately `restart_audio()` (lib recompile) does not reset whatever mechanism within sc that gets jammed/backlogged on a time shift. my steps to reproduce:

- boot norns, running `awake`, connect via `screen`, adjust time with `sudo date --set="1:00:00"`
- connect to wifi router
- connect to norns via ssh, run `htop`
- check for timeshift via screen (or just listen for `awake` to stop)
- run `maiden` and type `restart_audio()` into REPL
- `htop` still peaked. it takes about 2 minutes for sc to process the time shift (as of right now) which is followed by a huge bang of backed-up note triggers

i'm wondering if once sc gets into this timeshift state if it can even process incoming commands, ie, if we wanted to issue a graceful shutdown.

the better approach would likely be to shut down sc prior to activating a wifi router connection, monitor the date, and then possibly even just self-restart matron (as to avoid writing a secondary handshake negotiation).

will keep working on it but very open to suggestions and ideas.

**Comment by artfwo** [comment]
@tehn does restarting the server (s.reboot) help?

**Comment by tehn** [comment]
on timeshift, sc is totally 100% hosed.

to reproduce:

- boot norns, `screen` in. `sudo date --set="1:00:00"` then `./stop.sh` then `./matron.sh > /dev/null &` then `sclang` (so we have a sc REPL)
- turn on `awake`, activate wifi
- on time shift, sc (in `screen`) is stuck. commands can be typed in but they are not processed... enter just gives a new line

**Pull request merged**
