### PR TITLE
Disable acceleration within menu

### PR DESCRIPTION
**Pull request by nf**
This is a definite improvement, if not a fine solution.
Tested navigating through very long and very short menus alike,
and it seems good.

Issue #376

### CODE REVIEW

**Comment by antonhornquist** [comment]
an alternative for the long-parameters-list use case is to add some kind of grouping of parameters and the possibility to jump to the next / previous group, and have acceleration disabled

**Comment by antonhornquist** [comment]
come to think of it, separators imply grouping, so that could probably be used for jumps

**Comment by antonhornquist** [comment]
merg this? @tehn @catfact

**Comment by catfact** [comment]
sure

**Comment by antonhornquist** [comment]
i tried this fix out again, more thoroughly. noted that this not only disables acceleration for enc2 == menu-navigation-cursor-encoder (as i first thought) but all encoders thus affecting main volume knob and parameter value changes.

so with this parameters would be changed with acceleration in script mode and without in menu, which is inconsistent.

afaict the idea of #376 is to address twitchy-ness in navigating the menu cursor?

i suggest to close this pr and keep issue #376 open

**Comment by nf** [comment]
@antonhornquist if you have suggestions for improving a pull request you needn't close it; that just prevents me from fixing it.

I modified the change to only affect encoder 2 and sent #480.

**Pull request closed without merging**
