### PR TITLE
various screen fixes

### PR DESCRIPTION
**Pull request by tehn**
fixes https://github.com/monome/norns/issues/412

fixes https://github.com/monome/norns/issues/410

fixes https://github.com/monome/norns/issues/395

also adds `screen.pixel(x,y)` (lua)

### CODE REVIEW

**Comment by tehn** [comment]
added one more fix to menu display

fixes https://github.com/monome/norns/issues/416

**Comment by tehn** [comment]
so i think i got everything. unfortunately you don't have hardware at the moment to check!

**Comment by markwheeler** [comment]
Ha yep, actually I don't have the build environment setup anyway (only been doing lua and sc stuff so far).

Looking at the code the fixes look like they make sense.

However I would suggest also removing the half pixel offset from `screen_arc`, `screen_rect`, `screen_move` and `screen_line`. The offset only really makes sense if you are drawing with an odd-width stroke which seems like a confusing assumption to make. Thoughts?

**Comment by tehn** [comment]
FYI the dev chain is all built in on norns. to recompile:

```
cd norns
git pull
./waf
./stop.sh
./start.sh
```

and you'll be up and running.

perhaps i'm misunderstanding cairo--- i added the offsets after some googling as a result of initial weird rendering issues.

is pixel 0,0 translated as the area between (-0.5,-0.5) and (0.5,0.5) or is it (0,0) to (1,1)?

looking for references now...

**Comment by markwheeler** [comment]
I think this explains it: https://www.cairographics.org/FAQ/#sharp_lines

**Comment by tehn** [comment]
thanks for the link, that was the one i read way in the past and had forgotten.

so you imagine it's best to let users figure out the offset business on their own? as the current hack isn't a real solution clearly.

**Comment by markwheeler** [comment]
Oh I didn't answer your earlier question: When Cairo draws a 1px rect at '0,0' it is exactly filling the first pixel, which could be described as the area from 0-1 on a graph.

Yes I think if we stick to the default cairo way of doing things we'll at least be in alignment with how most screen drawing systems work. And yep I'm sure some folks will draw 1 pixel lines and wonder why they're blurry but at least when they end up at that link or similar it'll get them on track!

Of course this change will throw off some of the current UI, we'll have to do a pass to see what needs tweaking.

**Comment by tehn** [comment]
checking the UI now. `rect` is really off with integers using `stroke` so i'm offsetting the LEVELS page with the bars. other scripts with normals lines seem fine ie awake and playfair

**Comment by markwheeler** [comment]
Hmm I would have expected any on-pixel line drawing to now need to be shifted on the script side (eg, in awake) in order to stay sharp. Think I need to test this on device! :D

**Comment by tehn** [comment]
> Hmm I would have expected any on-pixel line drawing to now need to be shifted on the script side (eg, in awake) in order to stay sharp. Think I need to test this on device! :D

i expected it as well, but playfair and awake look identical to as before.

**Comment by tehn** [comment]
scratch that... _almost_ identical. there's some off-by-one pixel tuning now but it's minor

**Comment by tehn** [comment]
i think this is good to merge if you (or anyone) would like to approve the PR

**Pull request merged**
