### PR TITLE
add lattice

### PR DESCRIPTION
**Pull request by tyleretters**
based on #1280 !

example usage: https://github.com/tyleretters/lattice

```lua
lattice = require("lattice")

-- basic lattice usage
my_lattice = lattice:new()

-- make some tracks
track_a = my_lattice:new_track(1/2, function() print("half notes") end)
track_b = my_lattice:new_track(1/4, function() print("quarter notes") end)

-- optionally add a track that is disabled
track_c = my_lattice:new_track(1/8, function() print("eighth notes") end, false)

-- start the lattice
my_lattice:start()

-- user definable callbacks
my_lattice.downbeat = function(transport)
  print("downbeat", transport)
end

-- another one, but in in 5/4 and 128 ppqn
my_other_lattice = lattice:new(5, 128)

-- global lattice controls
my_lattice:stop()
my_lattice:start()
my_lattice:toggle()
my_lattice:destroy()
my_lattice:set_meter(7)
my_lattice:set_ppqn(48)

-- individual track controls
track_a.stop()
track_a.start()
track_a.toggle()
track_a.destroy()
track_a.set_division(1/7)

```

### CODE REVIEW

**Comment by tehn** [comment]
example/api looks great! will check out the code later today.

**Comment by ngwese** [comment]
Looking at this only at a code level I would recommendation using a metatable with `track` as well so the method invocation was consistent (`.` vs `:`)

**Comment by tyleretters** [comment]
that's a great point. i'll get that going. on a similar note, i dislike `my_lattice.downbeat = ...`. should we perhaps pass in the function with `new()`?

**Comment by tyleretters** [comment]
or this `my_lattice:set_downbeat(function(transport) print("downbeat", transport) end)`

**Comment by ngwese** [comment]
Sorry for the piecemeal comments, haven’t found a moment to provide detailed feedback. One additional thought to consider, `track` => `player`, in the sense that a player drives a sequence or plays a track.

**Comment by tyleretters** [comment]
i like the spirit of the idea but don't love the word `player`.

maybe `lattice` is too poetic and we could go with `sequencer` and `sequence`?

**Comment by pq** [comment]
at first blush i really like this.  cheers!

a quick API thought... perhaps consider using tables for passing (named) params?  that would make things more explicit and i think more legible.  for example:

```lua
 lattice:new(5, 128)
```

could become:

```lua
 lattice:new{meter = 5, ppqn = 128}
```

(doing away with a need for explanatory comments like  these:


```lua
  -- another one, but in in 5/4 and 128 ppqn
  -- my_other_lattice = lattice:new(5, 128)
```
)

`new_track` would benefit from this style especially imo.

**Comment by tyleretters** [comment]
@pq thanks! awesome idea to use a table for the args. refactored. this solved a couple other style issues, too!

also how about `track` -> `pattern` ?

updated usage examples: https://github.com/tyleretters/lattice/blob/main/lattice.lua

```lua
-- basic lattice usage (uses defaults)
my_lattice = lattice:new()

-- named params, each optional
my_lattice = lattice:new{
  meter = 4,
  ppqn = 96,
  callback = function(t) print("transport position:", t) end
}

-- make some patterns
pattern_a = my_lattice:new_pattern{
  division = 1/2,
  callback = function() print("half notes") end
}
pattern_b = my_lattice:new_pattern{
  division = 1/4,
  callback = function() print("quarter notes") end
}
pattern_c = my_lattice:new_pattern{
  division = 1/8,
  callback = function() print("eighth notes") end,
  enabled = false
}

-- start the lattice
my_lattice:start()
```

**Comment by ryanlaws** [comment]
This is a really cool feature and overall I like the API. A few suggestions:
- `clock.sync` is a perfectly reasonable default as `pulse`'s timing source, but exposing this for overriding would enhance its utility, enabling e.g. LFOs, modulated clock sources, arpeggiators with irregular patterns. 
- It is a little confusing to me that both `Lattice` and `Pattern` provide callbacks. They're definitely valuable in `Pattern` but they seem extraneous in the parent `Lattice`. The use case of keeping track of `s.transport` may be a non-issue as it is public to the instantiator of the `Lattice`.
- The type check on like 97 could be replaced with a simple `or` since the default is `false`, and that type checking could be moved to `Pattern:set_callback`. This seems computationally cheaper (which may be significant in this time-critical scenario) and would also reduce nesting in `Lattice.pulse`.
- Removing a pattern which isn't the last pattern could cause duplicate pattern IDs and potentially orphan a pattern based on the size-based ID generation method on L123. It's probably safer to initialize a per-`Lattice` ID counter and increment it for every new `Pattern`.
- Requiring passing the pattern itself to remove it as in `Lattice:destroy_pattern` feels weird to me, especially since it's just grabbing its `id` property. It does look like `Lattice.patterns` is public and so could be used to enumerate the patterns. Maybe removing a pattern by passing its `id` would feel less weird.

**Comment by tyleretters** [comment]
lots of refactoring: https://github.com/tyleretters/lattice

@ryanlaws

- interesting. i broke out `.pulse` into `.auto_pulse` and `:pulse`. you can now pass a flag in to disable the automatic behavior and then call `my_lattice:pulse()` manually if you wish. cool idea.
- good feedback on the dual callbacks. i removed the `Lattice` one and it actually smoked out a minor inconsistency with timings.
- good feedback on the type checking. updated.
- good point on the ID issues. i added a counter as you suggested. it still feels somewhat loose to me.
- yeah, i don't like passing the pattern to lattice to destroy it either. i had it the other way (with the ID) but there were some issues with that, too. I HAVE A NEW SOLUTION: `pattern_a:destroy()`
- i also removed the `lattice:set_ppqn()` method - if you need to update `ppqn` in real time this module isn't for you.

**Comment by tyleretters** [comment]
should i take a look at anything else on this one?

**Comment by tehn** [comment]
i'll give it another review!

**Comment by tehn** [comment]
i think the broad usefulness of this lib greatly improved with the addition of the manual pulse.

API suggestion: we've been avoiding the term "callback" in preference of "action" (ie in params), so it seems that should continue here?

**Comment by tyleretters** [comment]
yeah! @ryanlaws was right about that one for sure.

yes. i've renamed callback to action.

**Review by tehn — APPROVED** [review]

**Pull request merged**
