### PR TITLE
add ableton link clock module

### PR DESCRIPTION
**Pull request by artfwo**

### CODE REVIEW

**Comment by tehn** [comment]
rad!!

**Comment by ngwese** [comment]
excited to test this out! hopefully in the next few days.

**Comment by artfwo** [comment]
test script:

https://gist.github.com/artfwo/a0224ba7fc84792648d7924398c4f59a

**Comment by tehn** [comment]
happy to merge this into master so we can get some help testing ahead of documentation and examples. figure it's safe given it doesn't present breaking changes?

i can test once i knock out these new issues which came up from the recent update

super work @artfwo !

**Comment by artfwo** [comment]
alright, i'm gonna merge it then and go ahead with the playback sync features, also hopefully will write a better testing app this weekend.

**Pull request merged**
