### PR TITLE
Notate that wrap accepts integers; reimplement to be constant-time

### PR DESCRIPTION
**Pull request by sixolet**
fixes https://github.com/monome/norns/issues/1576

### CODE REVIEW

**Comment by tyleretters** [comment]
@sixolet initial review looks great! i can test in the next 24 hours or so.

are the crow commits supposed to be part of a separate PR?

**Comment by sixolet** [comment]
Okay, I did a little bit of git surgery to remove the weird merge commits or the commits that I already PRed or whatever happened there.

**Comment by tyleretters** [comment]
my test results look good! the behavior is 1:1. i approve the merge. (i don't have the permissions actually approve it on github.)

@ngwese there are two concerns - one is clarifying is for integers. i will let @sixolet speak to the constant-time / performance.

**Comment by catfact** [comment]
i provided the `while` in demonstration code as an alternative to a recursive version of the same thing. i don't claim its optimal and it is indeed only for integers (thank you.) 

regarding performance i'll note that the looped `wrap` is faster when it only needs to wrap once or twice, which is most of the time. lua's modulo operator has several hidden costs: metamethod lookup, two branches, and operating on doubles.

**Comment by sixolet** [comment]
I think they were merged already. I can do some git surgery to extract
them. I just switched to ff-only, I think the problem was I was merging
from upstream.

**Review by tehn — APPROVED** [review]

**Pull request merged**
