### PR TITLE
use jack system time for clock

### PR DESCRIPTION
**Pull request by artfwo**

### CODE REVIEW

**Comment by dndrks** [comment]
daaaaaaaaaang, really nice work:

image

close enough for ambient-electro-jazz!

**Comment by tehn** [comment]
this is looking great! happy to merge when you're ready.

**Comment by artfwo** [comment]
i think this is ready for review now, but it would also be cool to give it a few smoke tests before merging. 

unfortunately, keeping a jack client in matron might make the system/menu unusable in case jackd freezes and requires restarting (happens every so often on my device). matron might need to reinitialize clock client in this case at best (and crash at worst), so i would like to eventually isolate the jack client and add some error handling to gracefully handle those cases.

**Comment by artfwo** [comment]
and here are some quick crude performance metrics with a basic counter script scheduling a coroutine wakeup 100 times per beat. i've compared release, main and jack builds, the metric is CPU usage in percents.

the fastest implementation so far is current main branch, with JACK clock having a small performance impact as expected, and current stable release being the slowest, reaching as far as 8% CPU on my box.

norns_clock_cpu

**Comment by dndrks** [comment]
closing the loop -- i stress tested this branch for a few hours on some heavy coroutine traffic, external syncing (to/from MIDI as well as crow), and transport start/stop and things seem to be really really clean. i didn't notice any performance issues.

unless there are any other hesitations, i feel like this is super work, artem!!!

**Review by tehn — APPROVED** [review]

**Pull request merged**
