### PR TITLE
hid update start

### PR DESCRIPTION
**Pull request by okyeron**
I wanted to dig into HID with a keyboard and mouse today and I found it was really confusing.

I thought It might be better to have it's connection method work like grid and midi so I set about rewriting hid.lua

Thus a HID script could be much simpler:
```
local keyb = hid.connect(1)
function keyb.event(typ, code, val)
    print("hid.event ", typ, code, val)
end
```

This is not yet plugged into menu.lua to have hid devices show up in the SYSTEM menus.

I am also getting an error on device removal that I don't understand
```error: double free in device_hid.c```

### CODE REVIEW

**Comment by okyeron** [comment]
Been poking at this more today and device removal seems broken or funky. My old keyboard* shows up as 2 devices (keyboard and mouse types) so I'm guessing part of the problem - and one of those 2 is not getting removed properly.

With a USB mouse, I get the error i mentioned above twice when I unplug. The error is coming from `TEST_NULL_AND_FREE(di->codes[i]);` in `dev_hid_deinit(void *self)` in [device_hid.c](https://github.com/monome/norns/blob/440ad13f44f898ddf957c8a70fa89450ddb6428d/matron/src/device/device_hid.c#L151) but I don't understand enough about what's happening there.

*Apple Extended II with ADB->USB adapter.

**Comment by catfact** [comment]
thanks for looking into this, the feature has been pretty neglected since early-days hacking.

lucky issue 666
https://github.com/monome/norns/issues/666

**Comment by okyeron** [comment]
Just doing some reading/skimming of libevdev docs (to see if there's something about multiple interface devices)...

Query: in `device_hid.c` - in `TEST_NULL_AND_FREE` why is `free()` being called instead of `[libevdev_free()](https://www.freedesktop.org/software/libevdev/doc/0.2/group__init.html#gacd9fe760d15be25fc99ce469034bd78c)`?

**Comment by okyeron** [comment]
Little help?

Should this line https://github.com/monome/norns/blob/1d1b4a669a04c3a79f0748034b47d8418b1e16e1/matron/src/device/device_hid.c#L56 be using `d->dev `and not `dev`?

(like this?)
`if( libevdev_has_event_code(d->dev, type, code) ) `

Also, shouldn't there be a call to `libevdev_free(di->dev);`  in the `dev_hid_deinit` function?
https://github.com/monome/norns/blob/1d1b4a669a04c3a79f0748034b47d8418b1e16e1/matron/src/device/device_hid.c#L151

**Comment by okyeron** [comment]
OK - I think I solved the double free issue - there were event types that got ignored for length, so I queried for the max value for all types and it fixed the null codes.

Still have an issue with my keyboard adding 2 devices when plugged in and then only releasing one or not releasing either (not exactly sure which), but the devices keep multiplying on unplug/plug.

**Comment by tehn** [comment]
apologies for the delay, i'll be able to look at this by the end of the week.

**Comment by okyeron** [comment]
Writing up notes here for future reference:

we have 2 input device nodes:
`/dev/input/event0`
`/dev/input/event1`

[device_monitor.c](https://github.com/monome/norns/blob/1d1b4a669a04c3a79f0748034b47d8418b1e16e1/matron/src/device/device_monitor.c#L236) `handle_device()` sends `dev_list_remove(t, node)` once for each node.

[device_list.c](https://github.com/monome/norns/blob/1d1b4a669a04c3a79f0748034b47d8418b1e16e1/matron/src/device/device_list.c#L95) `dev_list_remove()` gets the request and removes the first node (event0). The second time around (event1)  in `dev_list_remove()` `dev_lookup_path(node)` returns null and does not process any further. My theory is this is because the system has already removed the node `/dev/input/event1` (since it's paired with event0) and `dev_lookup_path` wont resolve. 

Thus `ev->hid_remove.id` does not get set for the second node and it's not removed.

At the moment I am not sure how to fix or work around that. (thinking some more...) perhaps if device_monitor.c was able to determine the device id first, it could send that to a separate dev_list_remove function specifically for HID/event types?

**Comment by okyeron** [comment]
Circling back on this tonight...

Can someone tell me if I'm on the right track here:
The first time device_list.c is called - [this line](https://github.com/monome/norns/blob/1d1b4a669a04c3a79f0748034b47d8418b1e16e1/matron/src/device/device_list.c#L118) sets `dq.head` to NULL. 

The next time this function gets called for the second device removal [line 97](https://github.com/monome/norns/blob/1d1b4a669a04c3a79f0748034b47d8418b1e16e1/matron/src/device/device_list.c#L97) returns NULL because `dq.head` is now NULL in `dev_lookup_path()`

It looks like if I change [line 118](https://github.com/monome/norns/blob/1d1b4a669a04c3a79f0748034b47d8418b1e16e1/matron/src/device/device_list.c#L118) to 
```
if(dq.head == dn) { dq.head = dn->next; }
```
The second device gets removed. (yay!)

My question - Is this OK as is?  Or... does `dq.size` needs to be checked before `dq.head` is set to `dn->next` or to `null` (if size is zero or 1) ?

**Comment by tehn** [comment]
@okyeron has this been working for you?

**Comment by okyeron** [comment]
Yes it has.

**Comment by catfact** [comment]
it doesnt seem like checking size would be a bad idea at all

**Comment by catfact** [comment]
@okyeron sorry this has been languishing for weeks and weeks. i for one have barely had time to use norns hardware and each session is kinda laser-focused on DSP issues. 

the code looks fine to me but i'd like to confirm on hardware. do you maybe have some kind of test script you've used, that we could take for a spin?

**Comment by okyeron** [comment]
I'll see if there's a test script i can dig up in the morning. I've forgotten precisely where this left off, but it was working well for me with a variety of inputs (mouse, keyboard, wacom, etc)

**Comment by artfwo** [comment]
@okyeron i'm currently revising the vport api, the WIP PR is here: https://github.com/monome/norns/pull/698 

would you like to update this PR accordingly? otherwise, i can work on that when done with grid and midi improvements.

**Comment by okyeron** [comment]
FWIW- I'm really fuzzy on all this since I've not really touched norns in a month (waiting for 2.0 things to settle into a place where I could install and test).

@catfact Here's 2 gists of the (janky) sample hid code I was using:
https://gist.github.com/okyeron/c3a5af2c04d8daf32ef290fa9e7923f5
https://gist.github.com/okyeron/f959f8301329e4be8a18b477145c2f39

@artfwo I can take a look at the new vport api, but again - i'm really fuzzy on this right now. 

Is the arc code from that pull the best to use for reference?

**Comment by tehn** [comment]
@okyeron thanks for the gists! i can help test.

**Comment by artfwo** [comment]
@okyeron yes, i'm also working on grid and midi at the moment.

**Comment by okyeron** [comment]
@artfwo I will try to refresh myself on this tonight. If you get done with grid/midi quickly - please go ahead and add the needed changes here

**Comment by okyeron** [comment]
@artfwo - i made an attempt to update hid to the vport changes based on your arc changes and I can't get it working. hid.devices is empty. Device (mouse) connects and vports is populated but then I'm stuck.

**Comment by artfwo** [comment]
@okyeron sorry, i missed the edit for your last comment and pushed my hid module in the vport cleanup branch already. right now i'm going to cherry-pick some of your fixes above into https://github.com/monome/norns/pull/698 and continue working from there.

**Comment by okyeron** [comment]
apologies - I didn't realize those text edits would not send notifications. I'll try to make new comments in future.

the important bit is in the comment: https://github.com/monome/norns/pull/662#issuecomment-447229707 for fixing device_list.c - for devices getting properly removed.

**Comment by artfwo** [comment]
@okyeron thanks, I've cherry picked the relevant commits and will give some testing to removing devices too.

**Comment by artfwo** [comment]
as this has now been merged with https://github.com/monome/norns/pull/698, i'm closing the PR. thanks @okyeron for the matron fixes!

**Pull request closed without merging**
