### PR TITLE
Detect hid device class

### PR DESCRIPTION
**Pull request by catfact**
first step in addressing issue #1251 

- event type and code tables are now copied to HID device object on construction. [note 1]

- added small module `hid_device_class` to query event types and codes for specific interface profiles. currently this just detects whether a device is an ASCII keyboard or a mouse. [note 2]

- add `isAsciiKeyboard` and `isMouse` flags to the device object. these could be used for all kinds of purposes: change whether/how device is shown in menu, add keycode->charcode conversion and callback for key input, etc.

- add a pretty trivial utility function to `tabutil.lua`, which inverts keys/values in a shallow table. (if one is going to repeatedly test whether various values are present in the table, this is way more efficient than looping over it many times. maybe having it as a util function will encourage that optimization.)

- minor fixes to luadoc comments in `hid.lua`.

----

[1] might not really be necessary / desirable to copy all this data for every device, if flagging the interface type suffices.

[2] easy enough to add other profiles like tablets and gamepads, but i don't have any on hand ATM

### CODE REVIEW

**Review by tehn — COMMENTED** [review]
this looks great--- and super glad this can all be done in lua (i was in a misguided `evdev` wormhole)

i'll test this on device before merging, and then set upon some menu/global logic to handle focus.

thank you millions!

**Comment by tehn** [comment]
re #1 (copying data table) i don't think it's a big deal...

**Comment by ngwese** [comment]
super minor note. the ‘isAsciiKeyboard’ and friends should probably be `is_ascii_keyboard` (snake case) to match other APIs

**Comment by tehn** [comment]
tested on device--- works great.

**Comment by catfact** [comment]
renamed functions and fields to snake case, and removed some wayward debug prints. 

seems ok to me know? if approved, i can move forward with adding a text input class and a locale-switching mechanism.

**Review by tehn — APPROVED** [review]

**Pull request merged**
