### PR TITLE
fix tape play

### LINKED ISSUE #531: TAPE broke
regression!

TAPE record now only makes blank tapes.
TAPE plays not-blank tapes as silence.

### PR DESCRIPTION
**Pull request by antonhornquist**
fixes #531

### CODE REVIEW

**Comment by antonhornquist** [comment]
i suspect issue is in supecollider core, the default SynthDef for `SoundFile.cue` did not works on the device. i replaced it with an earlier one, and this should work.

https://github.com/supercollider/supercollider/commit/d41d61170285b6f984b935854a29815d8a74401e

https://github.com/supercollider/supercollider/pull/3713

**Comment by antonhornquist** [comment]
please test on your side.

**Comment by tehn** [comment]
will do.

**Comment by nf** [comment]
Great catch @antonhornquist.

(for my own edification) I'm trying to understand what changed, and can't see how the upstream changes could have broken for us.

The only external change I see is the args to the instrument went from

`| out, amp = 1, bufnum, sustain, ar = 0, dr = 0.01 gate = 1 |`

to

`|out, amp=1, bufnum, sustainTime, atk=0, rel=0, gate=1|`

But we don't seem to use any of these args? Unless there's some acton at a distance that I'm not seeing? Would love to figure out the root cause here.

**Comment by tehn** [comment]
tested on hardware, works!

**Comment by antonhornquist** [comment]
@nf the ugen graph is different too. 

Compare the custom SynthDef I added here with the core one at SCClassLibrary/Common/Files/SoundFile.sc

**Comment by antonhornquist** [comment]
@nf compare the files on the device. My own 3.9.3 SuperCollider installation has the working ugen in core. Not sure we’re running 3.9.3 on device...

This has now been acknowledged as a bug in 3.10 beta with - I believe - a fix upcomimg in 3.10. 

Anyhow, our norns tape logic will probably be rewritten and improved in the near future. :)

**Comment by tehn** [comment]
@antonhornquist wondering if the updated sc broke this again?

**Pull request merged**
